name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker
        uses: docker/login-action@v2
        env:
          N8N_BASIC_AUTH_ACTIVE: true
          N8N_BASIC_AUTH_USER: ${{ secrets.N8N_BASIC_AUTH_USER }}
          N8N_BASIC_AUTH_PASSWORD: ${{ secrets.N8N_BASIC_AUTH_PASSWORD }}
        with:
          username: ${{ secrets.N8N_BASIC_AUTH_USER }}
          password: ${{ secrets.N8N_BASIC_AUTH_PASSWORD }}

      # Add more steps as needed for the build process
